import { entitlementLimitReached, resolveEntitlements } from "../commerce/entitlements";
import {
	authSeller,
	hasPrimarySellerCredential,
	hashSecret,
	jsonResponse,
} from "../../platform/http/shared";

export type DeviceProvisionResult =
	| { ok: true }
	| { ok: false; response: Response };

/**
 * Shortest device secret the server will store.
 *
 * The Android client sends a random UUID (36 characters, ~122 bits), so this
 * rejects only malformed or hand-rolled values. It is a floor, not a strength
 * check — the server cannot verify entropy in a string it did not generate.
 */
export const MIN_DEVICE_SECRET_LENGTH = 20;

/**
 * Authorize a client-generated device secret after strong proof (OTP/passkey).
 * This is the single implementation used by legacy OTP, onboarding V2, and
 * passkey sign-in so plan caps and single-device recovery cannot drift.
 */
export async function provisionDeviceSecret(
	env: Env,
	seller: Record<string, unknown>,
	phone: string,
	deviceSecret: string,
): Promise<DeviceProvisionResult> {
	if (!phone || !deviceSecret) {
		return { ok: false, response: jsonResponse({ error: "auth" }, 401) };
	}
	// A device secret is a bearer credential: it and the phone number are the
	// whole of `authSeller`. It is generated by the client, so the server cannot
	// make it strong — but it can refuse one that plainly is not, and it has to,
	// because the value is stored as an unsalted SHA-256 and a short or guessable
	// secret is recoverable from a database copy.
	//
	// Enforced here rather than at a call site: completePhoneAuth required 20
	// characters and restoreFirebaseSession required only non-empty, so the same
	// account could be given a one-character credential depending on which
	// endpoint the client happened to use. This is the single sink both go
	// through, which makes it the only place the rule cannot be bypassed.
	if (deviceSecret.length < MIN_DEVICE_SECRET_LENGTH) {
		return {
			ok: false,
			response: jsonResponse({ error: "weak_device_secret", min_length: MIN_DEVICE_SECRET_LENGTH }, 400),
		};
	}
	if (await authSeller(env, phone, deviceSecret)) return { ok: true };

	const secretHash = await hashSecret(deviceSecret);
	const sellerId = String(seller.id);
	const hasPrimaryCredential = hasPrimarySellerCredential(seller);
	const deviceLimit = env.ENTITLEMENTS_ENABLED === "true"
		? (await resolveEntitlements(env, sellerId)).entitlements.max_concurrent_devices
		: null;

	if (deviceLimit) {
		const cap = deviceLimit.mode === "unlimited" ? null : Number(deviceLimit.value ?? 0);
		const extra = await env.orderak_db
			.prepare("SELECT COUNT(*) AS c FROM seller_devices WHERE seller_id=?")
			.bind(sellerId)
			.first<{ c: number }>();
		const used = (hasPrimaryCredential ? 1 : 0) + Number(extra?.c ?? 0);
		if (!hasPrimaryCredential) {
			await setPrimary(env, sellerId, secretHash);
			seller.secret = secretHash;
		} else if (cap === 1) {
			await replaceAllDevices(env, sellerId, secretHash);
		} else if (cap !== null && used >= cap) {
			const snapshot = await resolveEntitlements(env, sellerId);
			return {
				ok: false,
				response: entitlementLimitReached(snapshot, "max_concurrent_devices"),
			};
		} else {
			await addDevice(env, sellerId, secretHash);
		}
		return { ok: true };
	}

	const plan = await env.orderak_db.prepare(
		`SELECT p.multi_device_enabled FROM subscriptions s JOIN plans p ON p.id=s.plan_id
		 WHERE s.seller_id=? AND s.status='active' AND p.active=1
		 ORDER BY s.id DESC LIMIT 1`,
	).bind(sellerId).first<{ multi_device_enabled: number }>();
	const freePlan = plan
		? null
		: await env.orderak_db
			.prepare("SELECT multi_device_enabled FROM plans WHERE id='free'")
			.first<{ multi_device_enabled: number }>();

	if (!hasPrimaryCredential) {
		await setPrimary(env, sellerId, secretHash);
		seller.secret = secretHash;
	} else if (Number(plan?.multi_device_enabled ?? freePlan?.multi_device_enabled ?? 0) === 1) {
		await addDevice(env, sellerId, secretHash);
	} else {
		// Verified recovery on a single-device plan replaces every old session.
		await replaceAllDevices(env, sellerId, secretHash);
	}
	return { ok: true };
}

async function setPrimary(env: Env, sellerId: string, hash: string): Promise<void> {
	await env.orderak_db
		.prepare("UPDATE sellers SET secret=?,updated_at=datetime('now') WHERE id=?")
		.bind(hash, sellerId)
		.run();
}

async function addDevice(env: Env, sellerId: string, hash: string): Promise<void> {
	await env.orderak_db
		.prepare("INSERT OR IGNORE INTO seller_devices(seller_id,secret_hash) VALUES(?,?)")
		.bind(sellerId, hash)
		.run();
}

async function replaceAllDevices(env: Env, sellerId: string, hash: string): Promise<void> {
	await env.orderak_db.batch([
		env.orderak_db.prepare("UPDATE sellers SET secret=? WHERE id=?").bind(hash, sellerId),
		env.orderak_db.prepare("DELETE FROM seller_devices WHERE seller_id=?").bind(sellerId),
	]);
}
