export type Field = { name: string; label: string; type?: 'text' | 'number' | 'textarea' | 'select' | 'checkbox' | 'datetime'; required?: boolean; options?: string[]; placeholder?: string; defaultValue?: string | number | boolean };
export type ActionConfig = { label: string; endpoint: string; method?: 'POST' | 'PATCH' | 'PUT'; permission: string; description: string; confirm?: string; pathField?: string; fields: Field[] };

export const actions: Record<string, ActionConfig> = {
  buyers: { label: 'Restrict customer', endpoint: '/api/admin/v1/buyer-restrictions', permission: 'buyers:manage', description: 'Block a buyer at one store or across the platform. The reason and evidence are audited.', confirm: 'Apply this buyer restriction?', fields: [
    { name: 'buyer_phone', label: 'Customer phone', required: true }, { name: 'store_id', label: 'Store ID (blank = platform)' }, { name: 'reason', label: 'Reason', required: true, type: 'textarea' }, { name: 'evidence', label: 'Evidence reference', type: 'textarea' }, { name: 'expires_at', label: 'Expires at', type: 'datetime' },
  ] },
  capabilities: { label: 'Set store control', endpoint: '/api/admin/v1/store-controls', permission: 'capabilities:manage', description: 'Override an enforced store capability. A setting cannot bypass its deployment hard gate.', confirm: 'Apply this store-scoped runtime control?', fields: [
    { name: 'store_id', label: 'Store ID', required: true }, { name: 'capability_key', label: 'Enforced capability', type: 'select', options: ['orders.accepting', 'catalog.public', 'ads.eligible', 'referrals.enabled', 'ai.assistant'] }, { name: 'enabled', label: 'Enabled', type: 'checkbox', defaultValue: true }, { name: 'reason', label: 'Audited reason', type: 'textarea', required: true },
  ] },
  privacy: { label: 'Open privacy request', endpoint: '/api/admin/v1/buyer-privacy', permission: 'buyers:manage', description: 'Record a scoped customer data request without persisting the plaintext phone in the request record.', fields: [
    { name: 'buyer_phone', label: 'Customer phone', required: true }, { name: 'store_id', label: 'Store ID (blank = platform)' }, { name: 'request_type', label: 'Request type', type: 'select', options: ['access', 'correction', 'deletion', 'restriction'], defaultValue: 'access' }, { name: 'notes', label: 'Evidence and notes', type: 'textarea', required: true },
  ] },
  coupons: { label: 'Create coupon', endpoint: '/api/admin/v1/coupons', permission: 'coupons:manage', description: 'Create or update a coupon. Coupon pricing is not injected into Google Play checkout.', fields: [
    { name: 'code', label: 'Code', required: true }, { name: 'discount_type', label: 'Discount type', type: 'select', options: ['percentage', 'fixed'], defaultValue: 'percentage' }, { name: 'value', label: 'Value', type: 'number', required: true }, { name: 'max_uses', label: 'Maximum uses', type: 'number', defaultValue: 0 }, { name: 'expires_at', label: 'Expires at', type: 'datetime' }, { name: 'active', label: 'Active', type: 'checkbox', defaultValue: true },
  ] },
  affiliate: { label: 'Referral settings', endpoint: '/api/admin/v1/affiliate', permission: 'affiliate:manage', description: 'Update commission and payout policy. Financial mutations remain finance/owner scoped.', fields: [
    { name: 'commission_type', label: 'Commission type', type: 'select', options: ['percentage', 'fixed'] }, { name: 'commission_value', label: 'Commission value', type: 'number' }, { name: 'referral_bonus_type', label: 'Bonus type', type: 'select', options: ['percentage', 'fixed'] }, { name: 'referral_bonus_value', label: 'Bonus value', type: 'number' }, { name: 'min_payout_minor', label: 'Minimum payout (minor units)', type: 'number' }, { name: 'payout_info', label: 'Payout policy', type: 'textarea' },
  ] },
  ads: { label: 'Create ad', endpoint: '/api/admin/v1/ads', permission: 'ads:manage', description: 'Create a first-party placement with HTTPS creative and destination validation.', fields: [
    { name: 'title', label: 'Internal title', required: true }, { name: 'title_i18n', label: 'Localized title JSON', type: 'textarea', placeholder: '{"en":"...","ar":"..."}' }, { name: 'image_url', label: 'HTTPS image URL', required: true }, { name: 'click_url', label: 'HTTPS destination' }, { name: 'type', label: 'Placement type', type: 'select', options: ['banner', 'native'] }, { name: 'target_plan', label: 'Target plan', defaultValue: 'free' }, { name: 'frequency', label: 'Frequency', type: 'number', defaultValue: 1 }, { name: 'weight', label: 'Weight', type: 'number', defaultValue: 1 }, { name: 'starts_at', label: 'Starts at', type: 'datetime' }, { name: 'ends_at', label: 'Ends at', type: 'datetime' }, { name: 'active', label: 'Active', type: 'checkbox', defaultValue: true },
  ] },
  exports: { label: 'Request export', endpoint: '/api/admin/v1/exports', permission: 'export:manage', description: 'Artifacts expire in 24 hours. Sensitive exports require an action-bound password and TOTP authorization.', fields: [
    { name: 'export_type', label: 'Dataset', type: 'select', options: ['stores', 'buyers', 'subscriptions', 'support', 'audit'] }, { name: 'classification', label: 'Classification', type: 'select', options: ['internal', 'sensitive'] },
  ] },
  flags: { label: 'Add rollout rule', endpoint: '/api/admin/v1/flag-rules', permission: 'flags:manage', description: 'Rules are evaluated after hard gates, account restrictions and plan eligibility.', fields: [
    { name: 'flag_key', label: 'Flag key', required: true }, { name: 'scope_type', label: 'Scope', type: 'select', options: ['global', 'country', 'app_version', 'plan', 'seller', 'store', 'percentage'] }, { name: 'scope_value', label: 'Scope value' }, { name: 'min_version_code', label: 'Minimum app version', type: 'number' }, { name: 'max_version_code', label: 'Maximum app version', type: 'number' }, { name: 'rollout_percentage', label: 'Rollout percentage', type: 'number' }, { name: 'value', label: 'Enabled', type: 'checkbox', defaultValue: true }, { name: 'priority', label: 'Priority', type: 'number', defaultValue: 100 }, { name: 'reason', label: 'Audited reason', type: 'textarea', required: true },
  ] },
  versions: { label: 'Add version policy', endpoint: '/api/admin/v1/app-versions', permission: 'versions:manage', description: 'Version policy can warn, force update, deny emergency versions or place the app in maintenance.', fields: [
    { name: 'platform', label: 'Platform', type: 'select', options: ['android'], defaultValue: 'android' }, { name: 'country_code', label: 'Country (blank = global)' }, { name: 'channel', label: 'Channel', type: 'select', options: ['production', 'internal'] }, { name: 'recommended_version_code', label: 'Recommended version', type: 'number' }, { name: 'minimum_version_code', label: 'Minimum version', type: 'number' }, { name: 'blocked_version_codes', label: 'Blocked versions (JSON array)', placeholder: '[101,102]' }, { name: 'store_url', label: 'Google Play URL' }, { name: 'enforce_after', label: 'Grace deadline', type: 'datetime' }, { name: 'maintenance_mode', label: 'Maintenance mode', type: 'checkbox' }, { name: 'reason', label: 'Audited reason', type: 'textarea', required: true },
  ] },
  announcements: { label: 'New announcement', endpoint: '/api/admin/v1/announcements', permission: 'announcements:manage', description: 'Publish a scheduled message to all sellers or one plan.', fields: [
    { name: 'title_i18n', label: 'Localized title JSON', type: 'textarea', required: true, placeholder: '{"en":"...","ar":"..."}' }, { name: 'body_i18n', label: 'Localized body JSON', type: 'textarea', required: true }, { name: 'target_plan', label: 'Target plan', defaultValue: 'all' }, { name: 'starts_at', label: 'Starts at', type: 'datetime' }, { name: 'ends_at', label: 'Ends at', type: 'datetime' }, { name: 'active', label: 'Active', type: 'checkbox', defaultValue: true },
  ] },
  emails: { label: 'Save template translation', endpoint: '/api/admin/v1/email-templates', pathField: 'key', permission: 'emails:manage', description: 'Save an audited Arabic or English template version. Event rows represent application attempts, not guaranteed delivery.', fields: [
    { name: 'key', label: 'Template key', required: true }, { name: 'lang', label: 'Language', type: 'select', options: ['en', 'ar'], defaultValue: 'en' }, { name: 'subject', label: 'Subject', required: true }, { name: 'html', label: 'HTML body', type: 'textarea', required: true }, { name: 'text', label: 'Plain-text body', type: 'textarea', required: true },
  ] },
  macros: { label: 'Create support macro', endpoint: '/api/admin/v1/support-macros', permission: 'support:manage', description: 'Create a localized reply template. Agents remain responsible for reviewing the final reply.', fields: [
    { name: 'name', label: 'Name', required: true }, { name: 'category', label: 'Category', defaultValue: 'general' }, { name: 'locale', label: 'Locale', type: 'select', options: ['en', 'ar', 'fr'], defaultValue: 'en' }, { name: 'body', label: 'Reply text', type: 'textarea', required: true }, { name: 'active', label: 'Active', type: 'checkbox', defaultValue: true },
  ] },
  content: { label: 'New content version', endpoint: '/api/admin/v1/content-configs', permission: 'content:manage', description: 'Create a draft legal, onboarding, support or pricing-display version.', fields: [
    { name: 'content_key', label: 'Content key', required: true, placeholder: 'legal.privacy' }, { name: 'locale', label: 'Locale', type: 'select', options: ['en', 'ar', 'fr'] }, { name: 'audience', label: 'Audience', defaultValue: 'all' }, { name: 'value', label: 'Content JSON', type: 'textarea', required: true }, { name: 'starts_at', label: 'Starts at', type: 'datetime' }, { name: 'ends_at', label: 'Ends at', type: 'datetime' },
  ] },
  settings: { label: 'Update setting', endpoint: '/api/admin/v1/settings', method: 'PUT', pathField: 'key', permission: 'settings:manage', description: 'Update an audited system setting. Runtime controls should use the governed controls pages.', confirm: 'Save this system setting?', fields: [
    { name: 'key', label: 'Setting key', required: true }, { name: 'value_json', label: 'JSON value', type: 'textarea', required: true },
  ] },
  theme: { label: 'Update theme', endpoint: '/api/admin/v1/theme', method: 'PUT', permission: 'settings:manage', description: 'Set accessible six-digit hex colors. Unsafe contrast combinations fall back to compiled defaults.', confirm: 'Publish these design tokens?', fields: [
    { name: 'primary', label: 'Primary', defaultValue: '#1E3A8A' }, { name: 'primary_strong', label: 'Primary strong', defaultValue: '#14275C' }, { name: 'primary_soft', label: 'Primary soft', defaultValue: '#EDF1FC' }, { name: 'primary_tint', label: 'Primary tint', defaultValue: '#3B5BA9' }, { name: 'canvas', label: 'Canvas', defaultValue: '#F5F7FC' }, { name: 'surface', label: 'Surface', defaultValue: '#FFFFFF' }, { name: 'ink', label: 'Ink', defaultValue: '#14141F' }, { name: 'muted', label: 'Muted', defaultValue: '#5C6470' }, { name: 'line', label: 'Line', defaultValue: '#E1E5EE' }, { name: 'danger', label: 'Danger', defaultValue: '#C1362B' }, { name: 'danger_soft', label: 'Danger soft', defaultValue: '#FBEAE8' }, { name: 'warning', label: 'Warning', defaultValue: '#9A6700' }, { name: 'warning_soft', label: 'Warning soft', defaultValue: '#FBF1DE' }, { name: 'accent', label: 'Accent', defaultValue: '#D4A017' },
  ] },
  roadmap: { label: 'Add roadmap item', endpoint: '/api/admin/v1/roadmap', permission: 'roadmap:manage', description: 'Add an internal roadmap item.', fields: [{ name: 'title_i18n', label: 'Localized title JSON', type: 'textarea', required: true }, { name: 'body_i18n', label: 'Description JSON', type: 'textarea' }, { name: 'status', label: 'Status', type: 'select', options: ['planned', 'in_progress', 'complete'] }, { name: 'priority', label: 'Priority', type: 'select', options: ['low', 'medium', 'high'] }, { name: 'owner', label: 'Owner' }, { name: 'target_date', label: 'Target date' }] },
  tasks: { label: 'Add task', endpoint: '/api/admin/v1/tasks', permission: 'tasks:manage', description: 'Create an internal delivery task.', fields: [{ name: 'title', label: 'Title', required: true }, { name: 'description', label: 'Description', type: 'textarea' }, { name: 'status', label: 'Status', type: 'select', options: ['todo', 'in_progress', 'blocked', 'done'] }, { name: 'priority', label: 'Priority', type: 'select', options: ['low', 'medium', 'high', 'critical'] }, { name: 'assignee', label: 'Assignee' }, { name: 'due_date', label: 'Due date' }] },
  releases: { label: 'Add release', endpoint: '/api/admin/v1/releases', permission: 'releases:manage', description: 'Record a release and deployment state.', fields: [{ name: 'component', label: 'Component', required: true }, { name: 'version', label: 'Version', required: true }, { name: 'deployment_status', label: 'Status', type: 'select', options: ['planned', 'staged', 'deployed', 'rolled_back'] }, { name: 'notes', label: 'Notes', type: 'textarea' }] },
  bugs: { label: 'Report bug', endpoint: '/api/admin/v1/bugs', permission: 'bugs:manage', description: 'Record an internal defect and accountable owner.', fields: [{ name: 'title', label: 'Title', required: true }, { name: 'severity', label: 'Severity', type: 'select', options: ['low', 'medium', 'high', 'critical'], defaultValue: 'medium' }, { name: 'affected_area', label: 'Affected area' }, { name: 'owner', label: 'Owner' }, { name: 'fix_notes', label: 'Notes', type: 'textarea' }] },
  prompts: { label: 'Add prompt asset', endpoint: '/api/admin/v1/prompts', permission: 'prompts:manage', description: 'Create a prompt asset. Runtime selection remains constrained by the AI environment gate.', fields: [{ name: 'name', label: 'Name', required: true }, { name: 'provider', label: 'Provider', type: 'select', options: ['deepseek', 'openai', 'claude', 'gemini'] }, { name: 'model', label: 'Model' }, { name: 'system_prompt', label: 'System prompt', type: 'textarea', required: true }, { name: 'active', label: 'Active', type: 'checkbox' }] },
  docs: { label: 'Add document link', endpoint: '/api/admin/v1/project-docs', permission: 'docs:manage', description: 'Add a documentation link for internal operators.', fields: [{ name: 'title', label: 'Title', required: true }, { name: 'url', label: 'HTTPS URL', required: true }, { name: 'category', label: 'Category' }, { name: 'description', label: 'Description', type: 'textarea' }] },
  design: { label: 'Add design asset', endpoint: '/api/admin/v1/design-assets', permission: 'design:manage', description: 'Register a design source or approved export.', fields: [{ name: 'name', label: 'Name', required: true }, { name: 'type', label: 'Type', type: 'select', options: ['figma', 'canva', 'exported'], defaultValue: 'figma' }, { name: 'url', label: 'HTTPS URL', required: true }, { name: 'screen_ref', label: 'Screen reference' }] },
  tags: { label: 'Add endpoint', endpoint: '/api/admin/v1/endpoints', permission: 'endpoints:manage', description: 'Record backend endpoint ownership and implementation state.', fields: [{ name: 'method', label: 'Method', type: 'select', options: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'] }, { name: 'path', label: 'Path', required: true }, { name: 'module', label: 'Module' }, { name: 'status', label: 'Status', type: 'select', options: ['implemented', 'partial', 'planned'] }, { name: 'notes', label: 'Notes', type: 'textarea' }] },
};
