ALTER TABLE plans ADD COLUMN max_categories INTEGER DEFAULT NULL;
ALTER TABLE plans ADD COLUMN max_products INTEGER DEFAULT NULL;
ALTER TABLE plans ADD COLUMN max_orders_per_month INTEGER DEFAULT NULL;
ALTER TABLE plans ADD COLUMN max_ai_requests_per_month INTEGER DEFAULT NULL;
ALTER TABLE plans ADD COLUMN max_team_members INTEGER DEFAULT NULL;
ALTER TABLE plans ADD COLUMN custom_domain_enabled INTEGER DEFAULT 0;
ALTER TABLE plans ADD COLUMN analytics_enabled INTEGER DEFAULT 0;
ALTER TABLE plans ADD COLUMN priority_support_enabled INTEGER DEFAULT 0;
UPDATE plans SET max_products=20,max_categories=5,max_orders_per_month=50,max_ai_requests_per_month=20,max_team_members=1 WHERE id='free';
UPDATE plans SET max_products=200,max_categories=20,max_orders_per_month=500,max_ai_requests_per_month=200,max_team_members=1,analytics_enabled=1 WHERE id='starter';
UPDATE plans SET max_products=NULL,max_categories=NULL,max_orders_per_month=NULL,max_ai_requests_per_month=NULL,max_team_members=5,analytics_enabled=1,priority_support_enabled=1 WHERE id='professional';
ALTER TABLE content_pages ADD COLUMN active INTEGER DEFAULT 1;
ALTER TABLE content_pages ADD COLUMN notes TEXT;
CREATE TABLE IF NOT EXISTS roadmap_items (id INTEGER PRIMARY KEY AUTOINCREMENT,title_i18n TEXT,body_i18n TEXT,status TEXT DEFAULT 'planned',priority TEXT DEFAULT 'medium',owner TEXT,target_date TEXT,sort_order INTEGER DEFAULT 0,created_at TEXT DEFAULT (datetime('now')),updated_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS project_tasks (id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,description TEXT,status TEXT DEFAULT 'todo',priority TEXT DEFAULT 'medium',assigned_to TEXT,related_area TEXT,created_at TEXT DEFAULT (datetime('now')),updated_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS api_endpoints (id INTEGER PRIMARY KEY AUTOINCREMENT,method TEXT NOT NULL,path TEXT NOT NULL,description_i18n TEXT,status TEXT DEFAULT 'implemented',docs_url TEXT,test_result TEXT,android_integration TEXT DEFAULT 'none',created_at TEXT DEFAULT (datetime('now')),updated_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS ai_prompts (id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,provider TEXT,model TEXT,version TEXT,prompt_text TEXT,test_notes TEXT,active INTEGER DEFAULT 1,created_at TEXT DEFAULT (datetime('now')),updated_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS design_assets (id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,type TEXT DEFAULT 'figma',url TEXT NOT NULL,screen_ref TEXT,created_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS releases (id INTEGER PRIMARY KEY AUTOINCREMENT,component TEXT NOT NULL,version TEXT NOT NULL,changelog_i18n TEXT,build_file_url TEXT,deployment_status TEXT DEFAULT 'pending',checklist_json TEXT,released_at TEXT,created_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS bugs (id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,severity TEXT DEFAULT 'medium',affected_area TEXT,status TEXT DEFAULT 'open',owner TEXT,fix_notes TEXT,created_at TEXT DEFAULT (datetime('now')),updated_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS project_docs (id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,category TEXT,url_or_path TEXT NOT NULL,created_at TEXT DEFAULT (datetime('now')));
CREATE INDEX IF NOT EXISTS idx_roadmap_status ON roadmap_items(status);
CREATE INDEX IF NOT EXISTS idx_tasks_status ON project_tasks(status);
CREATE INDEX IF NOT EXISTS idx_bugs_status ON bugs(status);
CREATE INDEX IF NOT EXISTS idx_api_status ON api_endpoints(status);
