/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.edge.jsonc --include-runtime=false --strict-vars=false --env-interface=EdgeEnv src/edge/worker-configuration.d.ts` (hash: 8870f8892cc065563aa421075a569414)
interface __BaseEnv_EdgeEnv {
	ASSETS: Fetcher;
	CANONICAL_HOST: string;
	THEME_ORIGIN: string;
	ADMIN_WORKER: Fetcher /* orderak-admin-worker */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_EdgeEnv {}
}
interface EdgeEnv extends __BaseEnv_EdgeEnv {}
