package app.orderak.seller.core.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

/**
 * GENERATED FILE — DO NOT EDIT BY HAND.
 *
 * Produced by services/backend/scripts/generate-design-system-fixture.ts from
 * DEFAULT_DESIGN_SYSTEM_SOURCE. Regenerate with, from services/backend:
 *
 *     pnpm run design-system:generate
 *
 * Every colour below was emitted by generateDesignSystem(), which fails on any
 * role pair below its required WCAG ratio. That build-time gate is the only
 * contrast enforcement in the system: colours reach the app through this file
 * and nowhere else, so hand-editing it removes the guarantee entirely.
 */
internal data class GeneratedTypeRole(
    val sizeSp: Float,
    val lineHeight: Float,
    val weight: Int,
    val letterSpacingEm: Float,
)

internal object GeneratedDesignSystem {
    const val GENERATOR_VERSION = "orderak-mcu-0.3.0+3"
    const val CONTENT_HASH = "6b95438c3fa8a37a8a7614882da4e0d44d2054ca7dd4317036c3040a62a6e0eb"
    const val MINIMUM_TOUCH_TARGET_DP = 48f
    const val FONT_FAMILY = "cairo"
    const val DEFAULT_CONTRAST = "standard"

    val contrasts: List<String> = listOf("standard", "medium", "high")

    fun colorScheme(contrast: String, dark: Boolean): ColorScheme {
        val mode = if (dark) "dark" else "light"
        return when (mode to normalizeContrast(contrast)) {
            "light" to "standard" -> LightStandard
            "light" to "medium" -> LightMedium
            "light" to "high" -> LightHigh
            "dark" to "standard" -> DarkStandard
            "dark" to "medium" -> DarkMedium
            "dark" to "high" -> DarkHigh
            else -> LightStandard
        }
    }

    fun extendedColors(contrast: String, dark: Boolean): OrderakExtendedColors {
        val mode = if (dark) "dark" else "light"
        return when (mode to normalizeContrast(contrast)) {
            "light" to "standard" -> LightStandardExtended
            "light" to "medium" -> LightMediumExtended
            "light" to "high" -> LightHighExtended
            "dark" to "standard" -> DarkStandardExtended
            "dark" to "medium" -> DarkMediumExtended
            "dark" to "high" -> DarkHighExtended
            else -> LightStandardExtended
        }
    }

    fun normalizeContrast(contrast: String): String =
        if (contrast in contrasts) contrast else "standard"

    val typography: Map<String, GeneratedTypeRole> = mapOf(
        "displayLarge" to GeneratedTypeRole(57f, 4f, 400, -0.0044f),
        "displayMedium" to GeneratedTypeRole(45f, 3.25f, 400, 0f),
        "displaySmall" to GeneratedTypeRole(36f, 2.75f, 400, 0f),
        "headlineLarge" to GeneratedTypeRole(32f, 2.5f, 400, 0f),
        "headlineMedium" to GeneratedTypeRole(28f, 2.25f, 400, 0f),
        "headlineSmall" to GeneratedTypeRole(24f, 2f, 400, 0f),
        "titleLarge" to GeneratedTypeRole(22f, 1.75f, 400, 0f),
        "titleMedium" to GeneratedTypeRole(16f, 1.5f, 500, 0.0094f),
        "titleSmall" to GeneratedTypeRole(14f, 1.25f, 500, 0.0071f),
        "bodyLarge" to GeneratedTypeRole(16f, 1.5f, 400, 0.0313f),
        "bodyMedium" to GeneratedTypeRole(14f, 1.25f, 400, 0.0179f),
        "bodySmall" to GeneratedTypeRole(12f, 1f, 400, 0.0333f),
        "labelLarge" to GeneratedTypeRole(14f, 1.25f, 500, 0.0071f),
        "labelMedium" to GeneratedTypeRole(12f, 1f, 500, 0.0417f),
        "labelSmall" to GeneratedTypeRole(11f, 1f, 500, 0.0455f),
    )

    val spacing: Map<String, Float> = mapOf(
        "space0" to 0f,
        "space1" to 4f,
        "space2" to 8f,
        "space3" to 12f,
        "space4" to 16f,
        "space6" to 24f,
        "space8" to 32f,
        "space10" to 40f,
        "space12" to 48f,
        "space16" to 64f,
    )

    val shapes: Map<String, Float> = mapOf(
        "extraSmall" to 4f,
        "small" to 8f,
        "medium" to 12f,
        "large" to 16f,
        "extraLarge" to 24f,
    )
}

private val LightStandard: ColorScheme = lightColorScheme(
    primary = Color(0xFF014D4E),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFB0EEEE),
    onPrimaryContainer = Color(0xFF054F50),
    inversePrimary = Color(0xFF95D1D2),
    secondary = Color(0xFF386664),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFBBECE8),
    onSecondaryContainer = Color(0xFF1F4E4C),
    tertiary = Color(0xFF166A58),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFA5F2DA),
    onTertiaryContainer = Color(0xFF005142),
    background = Color(0xFFF3FBFC),
    onBackground = Color(0xFF151D1E),
    surface = Color(0xFFF3FBFC),
    onSurface = Color(0xFF151D1E),
    surfaceVariant = Color(0xFFD6E5E7),
    onSurfaceVariant = Color(0xFF3B494B),
    surfaceTint = Color(0xFF296768),
    inverseSurface = Color(0xFF2A3233),
    inverseOnSurface = Color(0xFFEAF2F3),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD5),
    onErrorContainer = Color(0xFF930009),
    outline = Color(0xFF6B7A7C),
    outlineVariant = Color(0xFFBAC9CB),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFFF3FBFC),
    surfaceDim = Color(0xFFD4DBDC),
    surfaceContainer = Color(0xFFE7EFF0),
    surfaceContainerHigh = Color(0xFFE2EAEA),
    surfaceContainerHighest = Color(0xFFDCE4E5),
    surfaceContainerLow = Color(0xFFEDF5F6),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    primaryFixed = Color(0xFFB0EEEE),
    primaryFixedDim = Color(0xFF95D1D2),
    onPrimaryFixed = Color(0xFF002020),
    onPrimaryFixedVariant = Color(0xFF054F50),
    secondaryFixed = Color(0xFFBBECE8),
    secondaryFixedDim = Color(0xFFA0CFCC),
    onSecondaryFixed = Color(0xFF00201F),
    onSecondaryFixedVariant = Color(0xFF1F4E4C),
    tertiaryFixed = Color(0xFFA5F2DA),
    tertiaryFixedDim = Color(0xFF89D5BF),
    onTertiaryFixed = Color(0xFF002019),
    onTertiaryFixedVariant = Color(0xFF005142),
)

private val DarkStandard: ColorScheme = darkColorScheme(
    primary = Color(0xFF95D1D2),
    onPrimary = Color(0xFF003738),
    primaryContainer = Color(0xFF054F50),
    onPrimaryContainer = Color(0xFFB0EEEE),
    inversePrimary = Color(0xFF296768),
    secondary = Color(0xFFA0CFCC),
    onSecondary = Color(0xFF003735),
    secondaryContainer = Color(0xFF1F4E4C),
    onSecondaryContainer = Color(0xFFBBECE8),
    tertiary = Color(0xFF89D5BF),
    onTertiary = Color(0xFF00382D),
    tertiaryContainer = Color(0xFF005142),
    onTertiaryContainer = Color(0xFFA5F2DA),
    background = Color(0xFF0D1516),
    onBackground = Color(0xFFDCE4E5),
    surface = Color(0xFF0D1516),
    onSurface = Color(0xFFDCE4E5),
    surfaceVariant = Color(0xFF3B494B),
    onSurfaceVariant = Color(0xFFBAC9CB),
    surfaceTint = Color(0xFF95D1D2),
    inverseSurface = Color(0xFFDCE4E5),
    inverseOnSurface = Color(0xFF2A3233),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690004),
    errorContainer = Color(0xFF930009),
    onErrorContainer = Color(0xFFFFDAD5),
    outline = Color(0xFF849495),
    outlineVariant = Color(0xFF3B494B),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFF333B3B),
    surfaceDim = Color(0xFF0D1516),
    surfaceContainer = Color(0xFF192122),
    surfaceContainerHigh = Color(0xFF242B2C),
    surfaceContainerHighest = Color(0xFF2E3637),
    surfaceContainerLow = Color(0xFF151D1E),
    surfaceContainerLowest = Color(0xFF080F10),
    primaryFixed = Color(0xFFB0EEEE),
    primaryFixedDim = Color(0xFF95D1D2),
    onPrimaryFixed = Color(0xFF002020),
    onPrimaryFixedVariant = Color(0xFF054F50),
    secondaryFixed = Color(0xFFBBECE8),
    secondaryFixedDim = Color(0xFFA0CFCC),
    onSecondaryFixed = Color(0xFF00201F),
    onSecondaryFixedVariant = Color(0xFF1F4E4C),
    tertiaryFixed = Color(0xFFA5F2DA),
    tertiaryFixedDim = Color(0xFF89D5BF),
    onTertiaryFixed = Color(0xFF002019),
    onTertiaryFixedVariant = Color(0xFF005142),
)

private val LightMedium: ColorScheme = lightColorScheme(
    primary = Color(0xFF003C3C),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFF3A7677),
    onPrimaryContainer = Color(0xFFFFFFFF),
    inversePrimary = Color(0xFF95D1D2),
    secondary = Color(0xFF083D3B),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFF477572),
    onSecondaryContainer = Color(0xFFFFFFFF),
    tertiary = Color(0xFF003E32),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFF2B7967),
    onTertiaryContainer = Color(0xFFFFFFFF),
    background = Color(0xFFF3FBFC),
    onBackground = Color(0xFF151D1E),
    surface = Color(0xFFF3FBFC),
    onSurface = Color(0xFF0B1213),
    surfaceVariant = Color(0xFFD6E5E7),
    onSurfaceVariant = Color(0xFF2A393A),
    surfaceTint = Color(0xFF296768),
    inverseSurface = Color(0xFF2A3233),
    inverseOnSurface = Color(0xFFEAF2F3),
    error = Color(0xFF740006),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFD02C27),
    onErrorContainer = Color(0xFFFFFFFF),
    outline = Color(0xFF465557),
    outlineVariant = Color(0xFF617072),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFFF3FBFC),
    surfaceDim = Color(0xFFC0C8C9),
    surfaceContainer = Color(0xFFE2EAEA),
    surfaceContainerHigh = Color(0xFFD6DEDF),
    surfaceContainerHighest = Color(0xFFCBD3D4),
    surfaceContainerLow = Color(0xFFEDF5F6),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    primaryFixed = Color(0xFF3A7677),
    primaryFixedDim = Color(0xFF1D5E5E),
    onPrimaryFixed = Color(0xFFFFFFFF),
    onPrimaryFixedVariant = Color(0xFFFFFFFF),
    secondaryFixed = Color(0xFF477572),
    secondaryFixedDim = Color(0xFF2E5C5A),
    onSecondaryFixed = Color(0xFFFFFFFF),
    onSecondaryFixedVariant = Color(0xFFFFFFFF),
    tertiaryFixed = Color(0xFF2B7967),
    tertiaryFixedDim = Color(0xFF01604F),
    onTertiaryFixed = Color(0xFFFFFFFF),
    onTertiaryFixedVariant = Color(0xFFFFFFFF),
)

private val DarkMedium: ColorScheme = darkColorScheme(
    primary = Color(0xFFAAE7E8),
    onPrimary = Color(0xFF002B2C),
    primaryContainer = Color(0xFF5F9B9B),
    onPrimaryContainer = Color(0xFF000000),
    inversePrimary = Color(0xFF075051),
    secondary = Color(0xFFB5E6E2),
    onSecondary = Color(0xFF002B2A),
    secondaryContainer = Color(0xFF6B9996),
    onSecondaryContainer = Color(0xFF000000),
    tertiary = Color(0xFF9FEBD4),
    onTertiary = Color(0xFF002C22),
    tertiaryContainer = Color(0xFF539E8A),
    onTertiaryContainer = Color(0xFF000000),
    background = Color(0xFF0D1516),
    onBackground = Color(0xFFDCE4E5),
    surface = Color(0xFF0D1516),
    onSurface = Color(0xFFFFFFFF),
    surfaceVariant = Color(0xFF3B494B),
    onSurfaceVariant = Color(0xFFCFDFE1),
    surfaceTint = Color(0xFF95D1D2),
    inverseSurface = Color(0xFFDCE4E5),
    inverseOnSurface = Color(0xFF242B2C),
    error = Color(0xFFFFD2CC),
    onError = Color(0xFF540003),
    errorContainer = Color(0xFFFF5449),
    onErrorContainer = Color(0xFF000000),
    outline = Color(0xFFA5B5B7),
    outlineVariant = Color(0xFF849395),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFF3E4647),
    surfaceDim = Color(0xFF0D1516),
    surfaceContainer = Color(0xFF22292A),
    surfaceContainerHigh = Color(0xFF2C3435),
    surfaceContainerHighest = Color(0xFF373F40),
    surfaceContainerLow = Color(0xFF171F20),
    surfaceContainerLowest = Color(0xFF030809),
    primaryFixed = Color(0xFFB0EEEE),
    primaryFixedDim = Color(0xFF95D1D2),
    onPrimaryFixed = Color(0xFF001415),
    onPrimaryFixedVariant = Color(0xFF003D3E),
    secondaryFixed = Color(0xFFBBECE8),
    secondaryFixedDim = Color(0xFFA0CFCC),
    onSecondaryFixed = Color(0xFF001414),
    onSecondaryFixedVariant = Color(0xFF083D3B),
    tertiaryFixed = Color(0xFFA5F2DA),
    tertiaryFixedDim = Color(0xFF89D5BF),
    onTertiaryFixed = Color(0xFF00150F),
    onTertiaryFixedVariant = Color(0xFF003E32),
)

private val LightHigh: ColorScheme = lightColorScheme(
    primary = Color(0xFF002929),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFF0A5253),
    onPrimaryContainer = Color(0xFFFFFFFF),
    inversePrimary = Color(0xFF95D1D2),
    secondary = Color(0xFF003231),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFF21504E),
    onSecondaryContainer = Color(0xFFFFFFFF),
    tertiary = Color(0xFF003329),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFF005344),
    onTertiaryContainer = Color(0xFFFFFFFF),
    background = Color(0xFFF3FBFC),
    onBackground = Color(0xFF151D1E),
    surface = Color(0xFFF3FBFC),
    onSurface = Color(0xFF000000),
    surfaceVariant = Color(0xFFD6E5E7),
    onSurfaceVariant = Color(0xFF000000),
    surfaceTint = Color(0xFF296768),
    inverseSurface = Color(0xFF2A3233),
    inverseOnSurface = Color(0xFFFFFFFF),
    error = Color(0xFF600004),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFF98000A),
    onErrorContainer = Color(0xFFFFFFFF),
    outline = Color(0xFF202F30),
    outlineVariant = Color(0xFF3D4C4E),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFFF3FBFC),
    surfaceDim = Color(0xFFB2BABB),
    surfaceContainer = Color(0xFFDCE4E5),
    surfaceContainerHigh = Color(0xFFCED6D7),
    surfaceContainerHighest = Color(0xFFC0C8C9),
    surfaceContainerLow = Color(0xFFEAF2F3),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    primaryFixed = Color(0xFF0A5253),
    primaryFixedDim = Color(0xFF00393A),
    onPrimaryFixed = Color(0xFFFFFFFF),
    onPrimaryFixedVariant = Color(0xFFFFFFFF),
    secondaryFixed = Color(0xFF21504E),
    secondaryFixedDim = Color(0xFF023938),
    onSecondaryFixed = Color(0xFFFFFFFF),
    onSecondaryFixedVariant = Color(0xFFFFFFFF),
    tertiaryFixed = Color(0xFF005344),
    tertiaryFixedDim = Color(0xFF003A2F),
    onTertiaryFixed = Color(0xFFFFFFFF),
    onTertiaryFixedVariant = Color(0xFFFFFFFF),
)

private val DarkHigh: ColorScheme = darkColorScheme(
    primary = Color(0xFFBDFBFC),
    onPrimary = Color(0xFF000000),
    primaryContainer = Color(0xFF91CDCE),
    onPrimaryContainer = Color(0xFF000E0E),
    inversePrimary = Color(0xFF075051),
    secondary = Color(0xFFC9F9F6),
    onSecondary = Color(0xFF000000),
    secondaryContainer = Color(0xFF9CCCC8),
    onSecondaryContainer = Color(0xFF000E0D),
    tertiary = Color(0xFFB4FFE8),
    onTertiary = Color(0xFF000000),
    tertiaryContainer = Color(0xFF85D1BB),
    onTertiaryContainer = Color(0xFF000E0A),
    background = Color(0xFF0D1516),
    onBackground = Color(0xFFDCE4E5),
    surface = Color(0xFF0D1516),
    onSurface = Color(0xFFFFFFFF),
    surfaceVariant = Color(0xFF3B494B),
    onSurfaceVariant = Color(0xFFFFFFFF),
    surfaceTint = Color(0xFF95D1D2),
    inverseSurface = Color(0xFFDCE4E5),
    inverseOnSurface = Color(0xFF000000),
    error = Color(0xFFFFECE9),
    onError = Color(0xFF000000),
    errorContainer = Color(0xFFFFAEA4),
    onErrorContainer = Color(0xFF220000),
    outline = Color(0xFFE3F3F5),
    outlineVariant = Color(0xFFB6C6C7),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFF4A5152),
    surfaceDim = Color(0xFF0D1516),
    surfaceContainer = Color(0xFF2A3233),
    surfaceContainerHigh = Color(0xFF353D3E),
    surfaceContainerHighest = Color(0xFF404849),
    surfaceContainerLow = Color(0xFF192122),
    surfaceContainerLowest = Color(0xFF000000),
    primaryFixed = Color(0xFFB0EEEE),
    primaryFixedDim = Color(0xFF95D1D2),
    onPrimaryFixed = Color(0xFF000000),
    onPrimaryFixedVariant = Color(0xFF001415),
    secondaryFixed = Color(0xFFBBECE8),
    secondaryFixedDim = Color(0xFFA0CFCC),
    onSecondaryFixed = Color(0xFF000000),
    onSecondaryFixedVariant = Color(0xFF001414),
    tertiaryFixed = Color(0xFFA5F2DA),
    tertiaryFixedDim = Color(0xFF89D5BF),
    onTertiaryFixed = Color(0xFF000000),
    onTertiaryFixedVariant = Color(0xFF00150F),
)

private val LightStandardExtended: OrderakExtendedColors = OrderakExtendedColors(
    warning = Color(0xFF755B00),
    warningSoft = Color(0xFFFFDF91),
    onWarning = Color(0xFFFFFFFF),
    onWarningContainer = Color(0xFF241A00),
    success = Color(0xFF1B6D24),
    successSoft = Color(0xFFA3F69C),
    onSuccess = Color(0xFFFFFFFF),
    onSuccessContainer = Color(0xFF002204),
    information = Color(0xFF0061A4),
    informationSoft = Color(0xFFD1E4FF),
    onInformation = Color(0xFFFFFFFF),
    onInformationContainer = Color(0xFF001D36),
    commerce = Color(0xFF814793),
    commerceSoft = Color(0xFFFAD7FF),
    onCommerce = Color(0xFFFFFFFF),
    onCommerceContainer = Color(0xFF330044),
    warningContainerOutline = Color(0xFF937309),
    successContainerOutline = Color(0xFF38873A),
    informationContainerOutline = Color(0xFF327ABF),
    commerceContainerOutline = Color(0xFF9C60AE),
    accent = Color(0xFF386664),
    onAccent = Color(0xFFFFFFFF),
    primaryTint = Color(0xFF95D1D2),
)

private val DarkStandardExtended: OrderakExtendedColors = OrderakExtendedColors(
    warning = Color(0xFFE9C259),
    warningSoft = Color(0xFF594400),
    onWarning = Color(0xFF3E2E00),
    onWarningContainer = Color(0xFFFFDF91),
    success = Color(0xFF88D982),
    successSoft = Color(0xFF005312),
    onSuccess = Color(0xFF003909),
    onSuccessContainer = Color(0xFFA3F69C),
    information = Color(0xFF9FCAFF),
    informationSoft = Color(0xFF00497D),
    onInformation = Color(0xFF003258),
    onInformationContainer = Color(0xFFD1E4FF),
    commerce = Color(0xFFEFB0FF),
    commerceSoft = Color(0xFF672E79),
    onCommerce = Color(0xFF4E1561),
    onCommerceContainer = Color(0xFFFAD7FF),
    warningContainerOutline = Color(0xFFCBA740),
    successContainerOutline = Color(0xFF6DBD6A),
    informationContainerOutline = Color(0xFF6EAFF7),
    commerceContainerOutline = Color(0xFFD493E6),
    accent = Color(0xFFA0CFCC),
    onAccent = Color(0xFF003735),
    primaryTint = Color(0xFF296768),
)

private val LightMediumExtended: OrderakExtendedColors = OrderakExtendedColors(
    warning = Color(0xFF594400),
    warningSoft = Color(0xFFE9C259),
    onWarning = Color(0xFFFFFFFF),
    onWarningContainer = Color(0xFF241A00),
    success = Color(0xFF005312),
    successSoft = Color(0xFF88D982),
    onSuccess = Color(0xFFFFFFFF),
    onSuccessContainer = Color(0xFF002204),
    information = Color(0xFF00497D),
    informationSoft = Color(0xFF9FCAFF),
    onInformation = Color(0xFFFFFFFF),
    onInformationContainer = Color(0xFF001D36),
    commerce = Color(0xFF672E79),
    commerceSoft = Color(0xFFEFB0FF),
    onCommerce = Color(0xFFFFFFFF),
    onCommerceContainer = Color(0xFF330044),
    warningContainerOutline = Color(0xFF846700),
    successContainerOutline = Color(0xFF2A7A2F),
    informationContainerOutline = Color(0xFF1F6EB1),
    commerceContainerOutline = Color(0xFF8E53A0),
    accent = Color(0xFF083D3B),
    onAccent = Color(0xFFFFFFFF),
    primaryTint = Color(0xFF95D1D2),
)

private val DarkMediumExtended: OrderakExtendedColors = OrderakExtendedColors(
    warning = Color(0xFFFFDF91),
    warningSoft = Color(0xFF4B3900),
    onWarning = Color(0xFF241A00),
    onWarningContainer = Color(0xFFFFEFCF),
    success = Color(0xFFA3F69C),
    successSoft = Color(0xFF00460E),
    onSuccess = Color(0xFF002204),
    onSuccessContainer = Color(0xFFC8FFBF),
    information = Color(0xFFD1E4FF),
    informationSoft = Color(0xFF003D6B),
    onInformation = Color(0xFF001D36),
    onInformationContainer = Color(0xFFEAF1FF),
    commerce = Color(0xFFFAD7FF),
    commerceSoft = Color(0xFF5A226D),
    onCommerce = Color(0xFF330044),
    onCommerceContainer = Color(0xFFFFEBFF),
    warningContainerOutline = Color(0xFFBD9A34),
    successContainerOutline = Color(0xFF60AF5D),
    informationContainerOutline = Color(0xFF5FA2E9),
    commerceContainerOutline = Color(0xFFC686D7),
    accent = Color(0xFFB5E6E2),
    onAccent = Color(0xFF002B2A),
    primaryTint = Color(0xFF075051),
)

private val LightHighExtended: OrderakExtendedColors = OrderakExtendedColors(
    warning = Color(0xFF3E2E00),
    warningSoft = Color(0xFFCBA740),
    onWarning = Color(0xFFFFFFFF),
    onWarningContainer = Color(0xFF000000),
    success = Color(0xFF003909),
    successSoft = Color(0xFF6DBD6A),
    onSuccess = Color(0xFFFFFFFF),
    onSuccessContainer = Color(0xFF000000),
    information = Color(0xFF003258),
    informationSoft = Color(0xFF6EAFF7),
    onInformation = Color(0xFFFFFFFF),
    onInformationContainer = Color(0xFF000000),
    commerce = Color(0xFF4E1561),
    commerceSoft = Color(0xFFD493E6),
    onCommerce = Color(0xFFFFFFFF),
    onCommerceContainer = Color(0xFF000000),
    warningContainerOutline = Color(0xFF674F00),
    successContainerOutline = Color(0xFF076019),
    informationContainerOutline = Color(0xFF005590),
    commerceContainerOutline = Color(0xFF743B86),
    accent = Color(0xFF003231),
    onAccent = Color(0xFFFFFFFF),
    primaryTint = Color(0xFF95D1D2),
)

private val DarkHighExtended: OrderakExtendedColors = OrderakExtendedColors(
    warning = Color(0xFFFFEFCF),
    warningSoft = Color(0xFF3E2E00),
    onWarning = Color(0xFF000000),
    onWarningContainer = Color(0xFFFFFFFF),
    success = Color(0xFFC8FFBF),
    successSoft = Color(0xFF003909),
    onSuccess = Color(0xFF000000),
    onSuccessContainer = Color(0xFFFFFFFF),
    information = Color(0xFFEAF1FF),
    informationSoft = Color(0xFF003258),
    onInformation = Color(0xFF000000),
    onInformationContainer = Color(0xFFFFFFFF),
    commerce = Color(0xFFFFEBFF),
    commerceSoft = Color(0xFF4E1561),
    onCommerce = Color(0xFF000000),
    onCommerceContainer = Color(0xFFFFFFFF),
    warningContainerOutline = Color(0xFFAF8C28),
    successContainerOutline = Color(0xFF53A252),
    informationContainerOutline = Color(0xFF5194DB),
    commerceContainerOutline = Color(0xFFB879C9),
    accent = Color(0xFFC9F9F6),
    onAccent = Color(0xFF000000),
    primaryTint = Color(0xFF075051),
)
